### ISSUE TITLE
Style guide for Fortran-FOSS group projects

### ISSUE THREAD

**Issue by milancurcic** [Fortran-FOSS-Programmers/Best_Practices#4]
Is this the correct repo to discuss and define the style guide for Fortran-FOSS group projects?

It is desirable to maintain uniform style within a project. To date, when contributing to FOODIE, I've been mostly replicating Stefano's style. However, a style guide sheet is needed since replicating somebody else's style will not always be possible, for example when starting a new project or when adding a language feature not previously used in an existing project.

My idea of a style guide would be something that is not 100% strict, but more like a list of "strongly recommended formats", a-la Pythons PEP8.

What do you think?

**Comment by szaghi** [comment]
@milancurcic  I am very sorry to be myself... thus unclear... my intention was also this: have a shared, colaborative guidelines for our projects in order to facilitate our collaboration. The answer is **yes** this is the best place for it!

And yes, a guidelines should only a suggestion not a mandatory rule. I agree to mimic the pep8 _soul_.

**Comment by zbeekman** [comment]
:+1:
